"""
Django settings for yukina project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from datetime import datetime

SECRET_KEY = '*82%j0_4)n41p2li+leo&5je3$wpanwm1@e@c2hq=#xao8#3+5'
MASTER_BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATABASE_DIR    = os.path.join(MASTER_BASE_DIR, 'db')
# PROJECT_ROOT    = os.path.dirname(__file__)
BASE_DIR        = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TEMPLATE_DIR    = os.path.join(BASE_DIR,'templates')
SITE_ID         = 1
ALLOWED_HOSTS               = ['*'] #Dev is '*'
DEBUG_PROPAGATE_EXCEPTIONS  = False #Dev is False
DEBUG                       = True #Dev is False
CORS_ORIGIN_ALLOW_ALL       = True
CORS_ALLOW_CREDENTIALS      = True
# sys.path.insert(0, os.path.join(PROJECT_ROOT, 'app'))

CORS_ORIGIN_WHITELIST = (
    'http://localhost:8002', 
    'http://localhost:8000'   
)

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)

INSTALLED_APPS = [
    'django_extensions',
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'app.fusioncharts',
    'app.authentication',
    'app.dashboard'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'scripts/logs/site'+datetime.today().strftime('%Y-%m-%d')+'.log',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers':['file'],
            'propagate': True,
            'level':'DEBUG',
        },
        'MYAPP': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
    }
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

STATICFILES_DIRS = [   
    os.path.join(BASE_DIR, 'assets/static/'),
]

MEDIAFILES_DIRS = os.path.join(BASE_DIR, 'assets/media/')

# AUTH_USER_MODEL                 = 'dashboard.User'
MESSAGE_STORAGE                 = 'django.contrib.messages.storage.cookie.CookieStorage'
STATICFILES_STORAGE             = 'django.contrib.staticfiles.storage.StaticFilesStorage'
EMAIL_BACKEND                   = 'des.backends.ConfiguredEmailBackend'

ROOT_URLCONF                    = 'yukina.urls'
WSGI_APPLICATION                = 'yukina.wsgi.application'
LANGUAGE_CODE                   = 'en-us'
TIME_ZONE                       = 'Asia/Jakarta'
ACCOUNT_AUTHENTICATION_METHOD   = 'username_email'
# X_FRAME_OPTIONS                 = 'Allow' #Dev is Allow
CSRF_COOKIE_SECURE              = False #Dev is False
SECURE_CONTENT_TYPE_NOSNIFF     = False #Dev is False
SECURE_BROWSER_XSS_FILTER       = False #Dev is False
SESSION_COOKIE_SECURE           = False #Dev is False
IMPORT_EXPORT_USE_TRANSACTIONS  = True
ACCOUNT_EMAIL_REQUIRED          = True
USE_I18N                        = True
USE_L10N                        = True
USE_TZ                          = False

STATIC_ROOT                     = '/assets/static/'
MEDIA_ROOT                      = 'assets/media/'
STATIC_URL                      = '/static/'
MEDIA_URL                       = '/media/'
LOGIN_URL                       = '/signin'
LOGOUT_URL                      = '/signout'
LOGOUT_REDIRECT_URL             = '/'
LOGIN_REDIRECT_URL              = '/'

ASGI_APPLICATION                = 'yukina.routing.application'

RECAPTCHA_PUBLIC_KEY            = '6LeU-9EUAAAAACRJY7yE_SqxFBEue9fPsC-YIGRw'
RECAPTCHA_PRIVATE_KEY           = '6LeU-9EUAAAAAHbOR_JVBEHkGEgEvZlJrdG7yXcW'
RECAPTCHA_VERIFY_REQUEST_TIMEOUT = 30
RECAPTCHA_DOMAIN                = 'www.recaptcha.net'
RECAPTCHA_REQUIRED_SCORE        = 0.85
RECAPTCHA_PROXY                 = {'http': 'http://127.0.0.1'}