# Generated by Django 3.0.6 on 2020-05-21 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorCurrentValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value_tds', models.FloatField(default=0)),
                ('value_ph', models.FloatField(default=0)),
                ('value_humidity', models.FloatField(default=0)),
                ('value_air_temperature', models.FloatField(default=0)),
                ('value_water_temperature', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
